import { Album, Photo } from "./types";

export const MOCK_ALBUMS_MAP: { [key: string]: { album: Album; photos: Photo[] } } = {
  "visit-greenland": {
    album: {
      id: "mock-1",
      title: "Visit Greenland",
      slug: "visit-greenland",
      description: "Commissioned by Visit Greenland, this collection captures the essence of Greenland's breathtaking glaciers, iceberg-filled fjords, and vibrant cultural heritage.",
      location: "Disko Bay, Greenland",
      date: "2023-03-15",
      cover_image_url: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?auto=format&fit=crop&q=80&w=1600",
      is_published: true,
      is_featured: true,
      tags: ["iceberg", "nature", "water"],
      lat: 69.22,
      lng: -51.10,
      country_code: "GL",
      location_path: [
        { id: "loc-na", name: "North America", type: "continent" },
        { id: "loc-gl", name: "Greenland", type: "country", iso_code: "GL", lat: 71.70, lng: -42.60 },
        { id: "loc-disko", name: "Disko Bay", type: "region", lat: 69.22, lng: -51.10 },
      ],
    },
    photos: [
      {
        id: "g1",
        url: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?auto=format&fit=crop&q=80&w=1600",
        thumbnail_url: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?auto=format&fit=crop&q=80&w=300",
        width: 1600,
        height: 1066,
        aspect_ratio: 1.5,
        location: "Disko Bay Glaciers",
        tags: ["glacier", "iceberg", "arctic", "nature", "blue", "water"],
        color_palette: ["#1F2B3E", "#4B6584", "#A5B1C2", "#D1D8E0", "#F1F2F6"],
        sort_order: 0,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 24-70mm F2.8 GM II",
          iso: 100,
          aperture: "f/8.0",
          shutter: "1/400s",
          focal_length: "35mm",
        },
      },
      {
        id: "g2",
        url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800",
        thumbnail_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=300",
        width: 800,
        height: 1200,
        aspect_ratio: 0.67,
        location: "Nuuk Color Cabins",
        tags: ["architecture", "cabin", "red", "snow", "winter", "cozy"],
        color_palette: ["#8B0000", "#D3D3D3", "#1A1A1A", "#FFFFFF", "#2F4F4F"],
        sort_order: 1,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 50mm F1.2 GM",
          iso: 250,
          aperture: "f/1.2",
          shutter: "1/1000s",
          focal_length: "50mm",
        },
      },
      {
        id: "g3",
        url: "https://images.unsplash.com/photo-1520637695736-3d36881c1626?auto=format&fit=crop&q=80&w=1600",
        thumbnail_url: "https://images.unsplash.com/photo-1520637695736-3d36881c1626?auto=format&fit=crop&q=80&w=300",
        width: 1600,
        height: 940,
        aspect_ratio: 1.7,
        location: "Ilulissat Icefjord",
        tags: ["iceberg", "sea", "ocean", "landscape", "aerial", "minimalist"],
        color_palette: ["#0C1E36", "#2D4B75", "#7D97BC", "#C4D4E8", "#EAF0F6"],
        sort_order: 2,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 70-200mm F2.8 GM OSS II",
          iso: 100,
          aperture: "f/5.6",
          shutter: "1/800s",
          focal_length: "135mm",
        },
      },
    ],
  },
  "inspired-by-iceland": {
    album: {
      id: "mock-2",
      title: "Inspired by Iceland",
      slug: "inspired-by-iceland",
      description: "An exploration of Iceland's raw volcanic landscapes, towering waterfalls, and moody black sand beaches under the midnight sun.",
      location: "Skógafoss, Iceland",
      date: "2024-06-20",
      cover_image_url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=1600",
      is_published: true,
      tags: ["landscape", "nature", "moody"],
      lat: 63.53,
      lng: -19.51,
      country_code: "IS",
      location_path: [
        { id: "loc-eu", name: "Europe", type: "continent" },
        { id: "loc-is", name: "Iceland", type: "country", iso_code: "IS", lat: 64.96, lng: -19.02 },
        { id: "loc-south-is", name: "Southern Region", type: "region", lat: 63.53, lng: -19.51 },
      ],
    },
    photos: [
      {
        id: "i1",
        url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=1600",
        thumbnail_url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=300",
        width: 1600,
        height: 1066,
        aspect_ratio: 1.5,
        location: "Skógafoss Waterfall",
        tags: ["waterfall", "nature", "mist", "rainbow", "green", "landscape"],
        color_palette: ["#0F1E19", "#294639", "#5F7D6B", "#A4BCA9", "#E1ECE5"],
        sort_order: 0,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 16-35mm F2.8 GM II",
          iso: 100,
          aperture: "f/11",
          shutter: "1/2s",
          focal_length: "18mm",
        },
      },
      {
        id: "i2",
        url: "https://images.unsplash.com/photo-1504893524553-ac55fce69cbf?auto=format&fit=crop&q=80&w=800",
        thumbnail_url: "https://images.unsplash.com/photo-1504893524553-ac55fce69cbf?auto=format&fit=crop&q=80&w=300",
        width: 800,
        height: 1200,
        aspect_ratio: 0.67,
        location: "Vík Black Sand Beach",
        tags: ["sea", "cliffs", "moody", "fog", "waves", "dark"],
        color_palette: ["#09090C", "#25262B", "#5C5E62", "#A6A8AB", "#D9DBDD"],
        sort_order: 1,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 24-70mm F2.8 GM II",
          iso: 400,
          aperture: "f/5.6",
          shutter: "1/250s",
          focal_length: "70mm",
        },
      },
    ],
  },
  "follow-the-tracks": {
    album: {
      id: "mock-3",
      title: "Follow the Tracks",
      slug: "follow-the-tracks",
      description: "Documenting the nomadic lifestyle and endless steppes of Mongolia, following the tracks of ancient horse cultures.",
      location: "Altai Mountains, Mongolia",
      date: "2025-09-05",
      cover_image_url: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&q=80&w=1600",
      is_published: true,
      tags: ["landscape", "mountains", "adventure"],
      lat: 48.01,
      lng: 89.06,
      country_code: "MN",
      location_path: [
        { id: "loc-as", name: "Asia", type: "continent" },
        { id: "loc-mn", name: "Mongolia", type: "country", iso_code: "MN", lat: 46.86, lng: 103.84 },
        { id: "loc-altai", name: "Bayan-Ölgii", type: "region", lat: 48.01, lng: 89.06 },
      ],
    },
    photos: [
      {
        id: "m1",
        url: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&q=80&w=1600",
        thumbnail_url: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&q=80&w=300",
        width: 1600,
        height: 1066,
        aspect_ratio: 1.5,
        location: "Altai Mountains",
        tags: ["mountains", "steppes", "clouds", "nomadic", "landscape", "adventure"],
        color_palette: ["#3D3528", "#6D5F4A", "#A19277", "#DCD5C5", "#1C2D37"],
        sort_order: 0,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 24-70mm F2.8 GM II",
          iso: 100,
          aperture: "f/7.1",
          shutter: "1/500s",
          focal_length: "28mm",
        },
      },
    ],
  },
  "shadows-of-anaga": {
    album: {
      id: "mock-4",
      title: "Shadows of Anaga",
      slug: "shadows-of-anaga",
      description: "Atmospheric wanderings through the ancient laurel cloud forests and dramatic coastal crests of Anaga Rural Park in Tenerife.",
      location: "Anaga, Tenerife, Spain",
      date: "2026-02-10",
      cover_image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1600",
      is_published: true,
      is_featured: true,
      tags: ["forest", "fog", "coast", "spain", "tenerife"],
      lat: 28.53,
      lng: -16.20,
      country_code: "ES",
      location_path: [
        { id: "loc-eu", name: "Europe", type: "continent" },
        { id: "loc-es", name: "Spain", type: "country", iso_code: "ES", lat: 40.46, lng: -3.74 },
        { id: "loc-canary", name: "Canary Islands", type: "region", lat: 28.29, lng: -16.62 },
        { id: "loc-tf", name: "Tenerife", type: "island", lat: 28.29, lng: -16.62 },
        { id: "loc-anaga", name: "Anaga", type: "spot", lat: 28.53, lng: -16.20 },
      ],
    },
    photos: [
      {
        id: "a1",
        url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1600",
        thumbnail_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=300",
        width: 1600,
        height: 1066,
        aspect_ratio: 1.5,
        location: "Anaga Cloud Forest",
        tags: ["forest", "laurel", "fog", "green", "trees", "nature"],
        color_palette: ["#142417", "#2D4430", "#5D7B61", "#94B398", "#D2E4D5"],
        sort_order: 0,
        exif: {
          camera: "Sony ILCE-7RM5",
          lens: "FE 24-70mm F2.8 GM II",
          iso: 200,
          aperture: "f/4.0",
          shutter: "1/125s",
          focal_length: "35mm",
        },
      },
    ],
  },
};

export const MOCK_ALBUMS_LIST: Album[] = Object.values(MOCK_ALBUMS_MAP).map(
  (entry) => {
    const coverPhoto = entry.photos.find((p) => p.url === entry.album.cover_image_url);
    return {
      ...entry.album,
      cover_color_palette: coverPhoto ? coverPhoto.color_palette : (entry.photos[0]?.color_palette || []),
    };
  }
);
